Paper Stone Scissors
vital987321/Learning_Python pull request #3
Opened 2024-01-22 13:43 UTC by vital987321

Learning_Python\school_homework\OOP_project_game

2024-01-26 10:35 UTC, PonomaryovVladyslav requested changes
переделать надо половину

2024-01-26 10:35 UTC, PonomaryovVladyslav commented on school_class_work/240107_decorator/tets.py
> +class Person(object):
Откуда тут вообще это?)

2024-01-26 10:35 UTC, PonomaryovVladyslav commented on school_class_work/240107_decorator/tets.py
> +@property
Проперти применяется к методам, а не к функциям, а называть параметр функции self, это стрелять себе в ногу

2024-01-26 10:35 UTC, PonomaryovVladyslav commented on school_homework/OOP_project_game/game.py
> +from settings import *
ничего и никогда не импортируй через звездочку

2024-01-26 10:35 UTC, PonomaryovVladyslav commented on school_homework/OOP_project_game/game.py
> +from game_exceptions import GameOver
А написать через запятую импорты религия не позволила?

2024-01-26 10:35 UTC, PonomaryovVladyslav commented on school_homework/OOP_project_game/game.py
> +from models import Player
И тут

2024-01-26 10:35 UTC, PonomaryovVladyslav commented on school_homework/OOP_project_game/game.py
> +    while True:
Ну вот у тебя есть блок который отвечает за введении имени и его валидацию, с точки зрения проектирования это долно быть как минимум две отдельные функции, отдельно валидация, и отдельно функция приема имени которая вызывает функцию с валидацией. И читать же проще будет и тесты писать сильно легче

2024-01-26 10:35 UTC, PonomaryovVladyslav commented on school_homework/OOP_project_game/game.py
> +        try:
туда же, две функции, селекл левел и валидейт селектед левел

2024-01-26 10:35 UTC, PonomaryovVladyslav commented on school_homework/OOP_project_game/models.py
> +        while True:
Тоже весь этот кусок я бы переписывал на отдельные функции и валидацию
А сравнивать результат со строкой вообще плохая затея, если уже так делать, то надо такую строку выносить в отдельную константу, тогда было бы норм

Отдельно функция с вводом от пользователя, отдельно валидация

2024-01-26 10:35 UTC, PonomaryovVladyslav commented on school_homework/OOP_project_game/models.py
> +        if player_attack == enemy_attack:
Выглядит не очень эстетичненько, я бы сделал для всех трех вариантов константы, и сделал словарь, у которого ключи это кортежи из двух строк (этих же констант), а значение это результат, и было бы гораздо удобнее и пользоваться и тестить

2024-01-26 10:35 UTC, PonomaryovVladyslav commented on school_homework/OOP_project_game/models.py
> +        else:
даже при таком коде элс тут не нужен, можно рейз сдивинуть на 4 пробела

2024-01-26 10:35 UTC, PonomaryovVladyslav commented on school_homework/OOP_project_game/game.py
> +                player.score += POINTS_FOR_KILLING if level == 'Normal' else POINTS_FOR_KILLING * HARD_MODE_MULTIPLIER
Эта логика должна быть методом игрока это раз, а два у тебя же вроде по заданию разные враги дают разное кол-во очков?

2024-01-26 10:35 UTC, PonomaryovVladyslav commented on school_homework/OOP_project_game/game.py
> +                enemy = Enemy(level)
И левел должен с каждой победой увеличиваться я это точно помню, не мешай между собой левел и уровень сложности игры, это два разных парметра вообще никак не связанных

2024-01-26 10:35 UTC, PonomaryovVladyslav commented on school_homework/OOP_project_game/game_exceptions.py
> +        player_record = [name, level, score]
Вот за такое надо делать какие-то прям гадости человеку)) Инит отвечает только за инициализацию!!! Совать бизнес логику в эксепшен это вообще перебор, не делай так пожалуйста никогда. Это должна быть отдельная функция, которая просто вызывается когда такой эксепшен случился, не более того

2024-01-26 10:35 UTC, PonomaryovVladyslav commented on school_homework/OOP_project_game/game_exceptions.py
> +        print('Exit game')
Называть классы стандартными именами тоже плохая идея) и инит все еще должен отвечать только за инициализацию, а у тебе еще и информированием называется

2024-01-26 10:35 UTC, PonomaryovVladyslav commented on school_homework/OOP_project_game/game.py
> +def get_status(player, enemy) -> None:
метод ничего не get, не сбивай людей с толку) он только print, так пусть так и называется

2024-01-26 10:35 UTC, PonomaryovVladyslav commented on school_homework/OOP_project_game/game.py
> +            with open(SCORE_FILE) as file:
Отдельная функция

2024-01-26 10:35 UTC, PonomaryovVladyslav commented on school_homework/OOP_project_game/game.py
> +            raise KeyboardInterrupt()
скобки тут не нужны) убери логику из инита))

2024-01-27 21:04 UTC, vital987321 commented on school_class_work/240107_decorator/tets.py
> +class Person(object):
Спасибо.

2024-01-27 21:04 UTC, vital987321 commented on school_class_work/240107_decorator/tets.py
> +@property
Это игнорируй. Не относится к домашнему заданию. Но все равно спасибо.

2024-01-27 21:04 UTC, vital987321 commented on school_homework/OOP_project_game/game.py
> +    while True:
Исправил

2024-01-27 21:07 UTC, vital987321 commented on school_homework/OOP_project_game/models.py
> +        while True:
Переписал. Отдельно инпут, отдельно валидация. Строку в константу.

2024-01-27 21:11 UTC, vital987321 commented on school_homework/OOP_project_game/game.py
> +from settings import *
Понял. Переписал.

2024-01-27 21:12 UTC, vital987321 commented on school_homework/OOP_project_game/game.py
> +from models import Player
есть

2024-01-27 21:12 UTC, vital987321 commented on school_homework/OOP_project_game/game.py
> +        try:
Сделал.

2024-01-27 21:13 UTC, vital987321 commented on school_homework/OOP_project_game/models.py
> +        if player_attack == enemy_attack:
Так и сделал.

2024-01-27 21:14 UTC, vital987321 commented on school_homework/OOP_project_game/models.py
> +        else:
Код уже несколько поменялся. Этого элса уже нет.

2024-01-27 21:25 UTC, vital987321 commented on school_homework/OOP_project_game/game.py
> +                player.score += POINTS_FOR_KILLING if level == 'Normal' else POINTS_FOR_KILLING * HARD_MODE_MULTIPLIER
Логику сделал методом игрока. А на счет того, что разные враги дают разное колличество очков, мне кажется это не так. Из задания:" Після успішної атаки у противника зменшуеться кількість життів. Гравець отримує 1 очко." и "Коли у противника закінчуються життя - гравець отримує додатково +5 очків і генерується новий противник". Вроди бы эти 2 условия всегда одинаковы.

2024-01-27 21:27 UTC, vital987321 commented on school_homework/OOP_project_game/game.py
> +                enemy = Enemy(level)
Мой косяк. Переделал. Теперь уровень сложности игры называю mode, а уровень сложности игрока - level.

2024-01-27 21:28 UTC, vital987321 commented on school_homework/OOP_project_game/game_exceptions.py
> +        player_record = [name, level, score]
Убрал логику из эксепшена.

2024-01-27 21:28 UTC, vital987321 commented on school_homework/OOP_project_game/game_exceptions.py
> +        print('Exit game')
Переименовал.

2024-01-27 21:28 UTC, vital987321 commented on school_homework/OOP_project_game/game.py
> +def get_status(player, enemy) -> None:
переименовал

2024-01-27 21:28 UTC, vital987321 commented on school_homework/OOP_project_game/game.py
> +            with open(SCORE_FILE) as file:
есть

2024-01-27 21:29 UTC, vital987321 commented on school_homework/OOP_project_game/game.py
> +            raise KeyboardInterrupt()
Убрал, убрал.

2024-01-29 10:38 UTC, PonomaryovVladyslav requested changes
Сильно лучше, но надо еще всякое поправить)

2024-01-29 10:38 UTC, PonomaryovVladyslav commented on school_homework/OOP_project_game/settings.py
> +ALLOWED_ATTACKS = {'1': 'Paper',
О, так у тебя есть уже допустимые атаки и моды, тогда тебе в тех местах где ты их используешь можно сделать новую функцию, типа get_allowed_options


```suggestion
def get_allowed_options(options_dict: dict) -> tuple:
    return tuple(option_dict.keys())
```
и просто подставлять нужный словарик)

2024-01-30 12:53 UTC, vital987321 commented on school_homework/OOP_project_game/game.py
> +        return False
Добавил сюда 2 кастомных эксепшена. Проверь правильно ли я это сделал. С эксепшенами могу начудить.

2024-01-30 12:56 UTC, vital987321 commented on school_homework/OOP_project_game/game.py
> +    if mode_input in ('1', '2'):
Убрал иф. Добавил функцию get_allowed_options(MODES)

2024-01-30 12:57 UTC, vital987321 commented on school_homework/OOP_project_game/game.py
> +                del enemy
Исправил.

2024-01-30 12:59 UTC, vital987321 commented on school_homework/OOP_project_game/models.py
> +        if attack_input in ('1', '2', '3'):
Есть.

2024-01-30 13:01 UTC, vital987321 commented on school_homework/OOP_project_game/models.py
> +            raise GameOver(self.name, self.mode, self.score)
Упс. Перекочевало с предыдущих комитов. Исправил.

2024-01-30 13:02 UTC, vital987321 commented on school_homework/OOP_project_game/settings.py
> +ALLOWED_ATTACKS = {'1': 'Paper',
Так и сделал.

2024-01-30 13:09 UTC, vital987321 commented
Комментарии очень ценные. Спасибо. Исправил.

2024-01-30 14:36 UTC, PonomaryovVladyslav commented on school_homework/OOP_project_game/game.py
> +def is_valid_name(name: str) -> bool:
Так, давай уже делать как взрослые) у тебя куча методов валидации разбросаны по всему проекту, это становится не читаемо, сделай файл validations.py, и засунь все туда, а дальше только импортируй

2024-01-30 14:37 UTC, PonomaryovVladyslav commented on school_homework/OOP_project_game/game.py
> +def is_valid_input_mode(mode_input: str) -> bool:
в validations.py

2024-01-30 14:37 UTC, PonomaryovVladyslav commented on school_homework/OOP_project_game/game.py
> +def get_allowed_options(options_dict: dict) -> tuple:
тоже в validations.py можно убрать или вообще еще один файл создать

2024-01-30 14:39 UTC, PonomaryovVladyslav commented on school_homework/OOP_project_game/game.py
> +    level = 1
Если у тебя есть неколько шагов инициализации, а потом еще несколько дейсвий связанных с самой игрой, которую нельзя начать без инициализации, не лучше ли засунуть это все в один красивый класс?)

2024-01-30 14:41 UTC, PonomaryovVladyslav commented on school_homework/OOP_project_game/game.py
> +    records = read_records()
Ну вот тоже, ты делаешь три действия над одной и тоже же переменной, не кажется ли тебе, что симпатичнее будет сделать для этого отдельный класс?)

2024-01-30 14:42 UTC, PonomaryovVladyslav commented on school_homework/OOP_project_game/game.py
> +def print_status(player: Player, enemy: Enemy) -> None:
я бы сделал это тоже как метод класса Game

2024-01-30 14:42 UTC, PonomaryovVladyslav commented on school_homework/OOP_project_game/game.py
> +def is_valid_menu_input(menu_input: str) -> bool:
в валидации)

2024-01-30 14:42 UTC, PonomaryovVladyslav commented on school_homework/OOP_project_game/models.py
> +    def __is_valid_input_attack(attack_input: str) -> bool:
Зачем это вообще метод класса? точно такая же валидация

2024-01-30 14:42 UTC, PonomaryovVladyslav commented on school_homework/OOP_project_game/models.py
> +    def __input_attack() -> str:
как и этот импут)

2024-01-30 14:43 UTC, PonomaryovVladyslav commented on school_homework/OOP_project_game/requirements.txt
> +https://github.com/ivnuk/ALEVEL_OOP_3/blob/master/requirements.md
зачем тут это?

2024-02-01 20:24 UTC, merged